begin;

with seed (
  titulo,
  objetivo,
  refeicao,
  calorias,
  proteina_g,
  tempo_preparo_min,
  is_premium,
  image_url,
  ativo,
  categorias,
  ingredientes,
  preparo
) as (
  values
  (
    'Omelete funcional com maca',
    'emagrecer',
    'cafe_da_manha',
    310,
    24,
    10,
    false,
    '',
    true,
    array['rapido','economico'],
    array['2 ovos','Tomate picado','Espinafre','1 maca pequena'],
    array['Bata os ovos com tomate e espinafre.','Prepare em frigideira antiaderente.','Sirva com a maca fatiada.']
  ),
  (
    'Iogurte proteico com chia e morango',
    'emagrecer',
    'cafe_da_manha',
    280,
    21,
    5,
    false,
    '',
    true,
    array['rapido','economico','pos_treino'],
    array['170g iogurte natural','1 colher de chia','Morangos picados','Canela'],
    array['Coloque o iogurte em uma tigela.','Adicione chia e morangos.','Finalize com canela.']
  ),
  (
    'Crepioca leve com cottage',
    'emagrecer',
    'cafe_da_manha',
    295,
    19,
    8,
    false,
    '',
    true,
    array['rapido','pre_treino'],
    array['1 ovo','2 colheres de tapioca','2 colheres de cottage','Oregano'],
    array['Misture o ovo com a tapioca.','Prepare na frigideira.','Recheie com cottage e oregano.']
  ),
  (
    'Smoothie verde com whey',
    'emagrecer',
    'cafe_da_manha',
    260,
    26,
    4,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['200ml agua','1 scoop whey','1/2 banana','Couve','Gelo'],
    array['Bata tudo no liquidificador.','Sirva imediatamente.']
  ),
  (
    'Aveia cremosa com banana e canela',
    'emagrecer',
    'cafe_da_manha',
    300,
    16,
    7,
    false,
    '',
    true,
    array['rapido','economico','pre_treino'],
    array['3 colheres de aveia','200ml leite desnatado','1/2 banana','Canela'],
    array['Aqueça o leite com a aveia.','Mexa ate engrossar.','Sirva com banana e canela.']
  ),

  (
    'Castanhas com pera',
    'emagrecer',
    'lanche_manha',
    210,
    6,
    2,
    false,
    '',
    true,
    array['rapido','economico'],
    array['15g castanhas','1 pera'],
    array['Separe as castanhas em porcao.','Consuma junto com a pera.']
  ),
  (
    'Iogurte natural com canela',
    'emagrecer',
    'lanche_manha',
    160,
    10,
    2,
    false,
    '',
    true,
    array['rapido','economico'],
    array['170g iogurte natural','Canela a gosto'],
    array['Coloque o iogurte em uma tigela.','Finalize com canela.']
  ),
  (
    'Maca fatiada com pasta de amendoim',
    'emagrecer',
    'lanche_manha',
    190,
    5,
    3,
    false,
    '',
    true,
    array['rapido','economico'],
    array['1 maca','1 colher de pasta de amendoim'],
    array['Fatie a maca.','Sirva com a pasta de amendoim.']
  ),
  (
    'Queijo branco com tomate cereja',
    'emagrecer',
    'lanche_manha',
    170,
    12,
    4,
    false,
    '',
    true,
    array['rapido','economico'],
    array['60g queijo branco','Tomate cereja','Oregano'],
    array['Monte um prato com queijo e tomate.','Finalize com oregano.']
  ),
  (
    'Shake leve de cacau',
    'emagrecer',
    'lanche_manha',
    180,
    20,
    3,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['200ml leite desnatado','1 scoop whey','1 colher de cacau'],
    array['Bata tudo no liquidificador.','Sirva gelado.']
  ),

  (
    'Frango grelhado com arroz integral',
    'emagrecer',
    'almoco',
    520,
    38,
    25,
    false,
    '',
    true,
    array['pos_treino'],
    array['150g frango','100g arroz integral','Salada verde','Azeite'],
    array['Grelhe o frango com temperos naturais.','Cozinhe o arroz integral.','Monte com salada e um fio de azeite.']
  ),
  (
    'Tilapia com pure de abobora',
    'emagrecer',
    'almoco',
    470,
    34,
    28,
    false,
    '',
    true,
    array['pos_treino'],
    array['140g tilapia','Abobora cozida','Brocolis','Limao'],
    array['Tempere e asse a tilapia.','Prepare o pure de abobora.','Sirva com brocolis.']
  ),
  (
    'Patinho moido com feijao e salada',
    'emagrecer',
    'almoco',
    490,
    36,
    24,
    false,
    '',
    true,
    array['economico','pos_treino'],
    array['130g patinho moido','80g feijao','Alface','Tomate'],
    array['Refogue o patinho moido.','Aqueça o feijao.','Monte com a salada fresca.']
  ),
  (
    'Omelete de forno com legumes',
    'emagrecer',
    'almoco',
    430,
    28,
    22,
    false,
    '',
    true,
    array['economico'],
    array['3 ovos','Abobrinha ralada','Cenoura ralada','Cebola'],
    array['Misture todos os ingredientes.','Leve ao forno ate firmar.','Sirva com salada.']
  ),
  (
    'Carne magra com quinoa e legumes',
    'emagrecer',
    'almoco',
    510,
    35,
    30,
    false,
    '',
    true,
    array['pos_treino'],
    array['130g carne magra','90g quinoa cozida','Abobrinha','Cenoura'],
    array['Grelhe a carne.','Cozinhe a quinoa.','Sirva com legumes salteados.']
  ),

  (
    'Shake leve de whey com gelo',
    'emagrecer',
    'lanche_tarde',
    180,
    25,
    3,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['1 scoop whey','200ml agua','Gelo'],
    array['Bata tudo rapidamente.','Sirva em seguida.']
  ),
  (
    'Iogurte proteico com kiwi',
    'emagrecer',
    'lanche_tarde',
    190,
    16,
    3,
    false,
    '',
    true,
    array['rapido'],
    array['170g iogurte proteico','1 kiwi'],
    array['Misture o iogurte com o kiwi picado.','Sirva gelado.']
  ),
  (
    'Wrap de alface com frango',
    'emagrecer',
    'lanche_tarde',
    220,
    23,
    8,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['100g frango desfiado','Folhas de alface','Tomate picado'],
    array['Distribua o frango sobre as folhas.','Adicione tomate e enrole.']
  ),
  (
    'Ovo cozido com cenoura baby',
    'emagrecer',
    'lanche_tarde',
    170,
    12,
    6,
    false,
    '',
    true,
    array['economico'],
    array['2 ovos cozidos','Cenoura baby'],
    array['Cozinhe os ovos.','Sirva com a cenoura baby.']
  ),
  (
    'Cottage com morangos',
    'emagrecer',
    'lanche_tarde',
    160,
    14,
    4,
    false,
    '',
    true,
    array['rapido'],
    array['4 colheres de cottage','Morangos picados'],
    array['Coloque o cottage em uma tigela.','Adicione os morangos por cima.']
  ),

  (
    'Peixe assado com legumes',
    'emagrecer',
    'jantar',
    430,
    33,
    30,
    false,
    '',
    true,
    array['pos_treino'],
    array['140g peixe branco','Abobrinha','Cenoura','Limao'],
    array['Tempere o peixe com limao.','Asse com os legumes.','Finalize com ervas frescas.']
  ),
  (
    'Sopa proteica de frango',
    'emagrecer',
    'jantar',
    360,
    30,
    25,
    false,
    '',
    true,
    array['economico','pos_treino'],
    array['120g frango desfiado','Abobora','Chuchu','Cebola'],
    array['Cozinhe os legumes.','Adicione o frango desfiado.','Acerte o sal e sirva.']
  ),
  (
    'Omelete noturno com salada',
    'emagrecer',
    'jantar',
    340,
    25,
    10,
    false,
    '',
    true,
    array['rapido','economico'],
    array['3 ovos','Tomate','Cebola','Folhas verdes'],
    array['Bata os ovos com tomate e cebola.','Prepare a omelete.','Sirva com salada.']
  ),
  (
    'Frango desfiado com couve-flor',
    'emagrecer',
    'jantar',
    390,
    31,
    20,
    false,
    '',
    true,
    array['pos_treino'],
    array['120g frango desfiado','Couve-flor','Alho','Azeite'],
    array['Refogue o alho com azeite.','Adicione a couve-flor e o frango.','Cozinhe ate ficar macio.']
  ),
  (
    'Carne magra com legumes salteados',
    'emagrecer',
    'jantar',
    410,
    32,
    18,
    false,
    '',
    true,
    array['pos_treino'],
    array['120g carne magra','Abobrinha','Brocolis','Cenoura'],
    array['Grelhe a carne.','Salteie os legumes.','Sirva tudo junto.']
  ),

  (
    'Panqueca proteica de banana com whey',
    'ganhar_massa',
    'cafe_da_manha',
    520,
    32,
    15,
    false,
    '',
    true,
    array['pre_treino','pos_treino'],
    array['2 ovos','3 colheres de aveia','1 banana','1 scoop whey'],
    array['Bata todos os ingredientes.','Prepare em frigideira ate dourar.','Sirva com fruta.']
  ),
  (
    'Sanduiche reforcado de ovos e ricota',
    'ganhar_massa',
    'cafe_da_manha',
    490,
    27,
    12,
    false,
    '',
    true,
    array['pre_treino','economico'],
    array['3 fatias de pao integral','3 ovos','2 colheres de ricota','Tomate'],
    array['Prepare os ovos mexidos.','Monte o sanduiche com ricota e tomate.']
  ),
  (
    'Overnight oats com whey e pasta de amendoim',
    'ganhar_massa',
    'cafe_da_manha',
    540,
    30,
    6,
    false,
    '',
    true,
    array['rapido','pre_treino','pos_treino'],
    array['200g iogurte natural','4 colheres de aveia','1 scoop whey','1 colher de pasta de amendoim'],
    array['Misture todos os ingredientes.','Deixe descansar na geladeira.','Consuma gelado.']
  ),
  (
    'Tapioca com frango e queijo minas',
    'ganhar_massa',
    'cafe_da_manha',
    510,
    29,
    14,
    false,
    '',
    true,
    array['pre_treino','pos_treino'],
    array['4 colheres de tapioca','100g frango desfiado','40g queijo minas'],
    array['Prepare a tapioca na frigideira.','Recheie com frango e queijo.']
  ),
  (
    'Vitamina hipercalorica de banana e aveia',
    'ganhar_massa',
    'cafe_da_manha',
    560,
    24,
    5,
    false,
    '',
    true,
    array['rapido','pre_treino'],
    array['300ml leite','2 bananas','3 colheres de aveia','1 colher de pasta de amendoim'],
    array['Bata tudo no liquidificador.','Sirva em seguida.']
  ),

  (
    'Sanduiche de peito de peru',
    'ganhar_massa',
    'lanche_manha',
    340,
    21,
    6,
    false,
    '',
    true,
    array['rapido','pre_treino'],
    array['2 fatias de pao integral','Peito de peru','Queijo branco','Alface'],
    array['Monte o sanduiche com os ingredientes frescos.']
  ),
  (
    'Banana com aveia e mel',
    'ganhar_massa',
    'lanche_manha',
    320,
    8,
    3,
    false,
    '',
    true,
    array['rapido','economico','pre_treino'],
    array['1 banana','2 colheres de aveia','1 colher de mel'],
    array['Fatie a banana.','Adicione aveia e mel por cima.']
  ),
  (
    'Iogurte com granola e whey',
    'ganhar_massa',
    'lanche_manha',
    360,
    24,
    4,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['170g iogurte natural','2 colheres de granola','1/2 scoop whey'],
    array['Misture todos os ingredientes.','Sirva gelado.']
  ),
  (
    'Torradas com pasta de amendoim e banana',
    'ganhar_massa',
    'lanche_manha',
    330,
    10,
    5,
    false,
    '',
    true,
    array['rapido','pre_treino','economico'],
    array['2 torradas integrais','1 colher de pasta de amendoim','1 banana'],
    array['Passe a pasta nas torradas.','Sirva com banana fatiada.']
  ),
  (
    'Queijo minas com castanhas e uva',
    'ganhar_massa',
    'lanche_manha',
    350,
    15,
    4,
    false,
    '',
    true,
    array['rapido'],
    array['60g queijo minas','15g castanhas','Uvas'],
    array['Monte um prato com os ingredientes.','Sirva como lanche.']
  ),

  (
    'Frango com macarrao integral',
    'ganhar_massa',
    'almoco',
    760,
    48,
    30,
    false,
    '',
    true,
    array['pos_treino'],
    array['170g frango','120g macarrao integral','Molho de tomate'],
    array['Cozinhe o macarrao.','Grelhe o frango.','Misture com molho leve.']
  ),
  (
    'Carne moida com arroz e feijao',
    'ganhar_massa',
    'almoco',
    720,
    44,
    28,
    false,
    '',
    true,
    array['economico','pos_treino'],
    array['150g carne moida','110g arroz','90g feijao','Salada'],
    array['Refogue a carne moida.','Aqueça arroz e feijao.','Monte o prato.']
  ),
  (
    'Tilapia com batata doce e legumes',
    'ganhar_massa',
    'almoco',
    690,
    40,
    30,
    false,
    '',
    true,
    array['pos_treino'],
    array['160g tilapia','180g batata doce','Legumes variados'],
    array['Asse a tilapia.','Cozinhe a batata doce.','Sirva com legumes.']
  ),
  (
    'Frango cremoso com pure de batata',
    'ganhar_massa',
    'almoco',
    740,
    46,
    32,
    false,
    '',
    true,
    array['pos_treino'],
    array['170g frango desfiado','200g pure de batata','Requeijao light'],
    array['Prepare o frango desfiado.','Faça o pure de batata.','Misture com requeijao e sirva.']
  ),
  (
    'Patinho com quinoa e abobora',
    'ganhar_massa',
    'almoco',
    680,
    42,
    29,
    false,
    '',
    true,
    array['pos_treino'],
    array['150g patinho','100g quinoa','Abobora assada'],
    array['Grelhe o patinho.','Cozinhe a quinoa.','Sirva com abobora.']
  ),

  (
    'Vitamina hipercalorica caseira',
    'ganhar_massa',
    'lanche_tarde',
    450,
    28,
    4,
    false,
    '',
    true,
    array['rapido','pre_treino'],
    array['300ml leite','Banana','Aveia','Pasta de amendoim'],
    array['Bata tudo no liquidificador ate ficar cremoso.']
  ),
  (
    'Iogurte proteico com granola e mel',
    'ganhar_massa',
    'lanche_tarde',
    390,
    22,
    3,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['170g iogurte proteico','3 colheres de granola','1 colher de mel'],
    array['Misture todos os ingredientes.','Sirva gelado.']
  ),
  (
    'Wrap de frango com queijo',
    'ganhar_massa',
    'lanche_tarde',
    420,
    29,
    10,
    false,
    '',
    true,
    array['rapido','pos_treino'],
    array['1 tortilha integral','120g frango desfiado','40g queijo branco','Alface'],
    array['Aqueça a tortilha.','Recheie com frango, queijo e alface.','Enrole e sirva.']
  ),
  (
    'Pao integral com ovos mexidos',
    'ganhar_massa',
    'lanche_tarde',
    370,
    21,
    9,
    false,
    '',
    true,
    array['pre_treino','economico'],
    array['2 fatias de pao integral','2 ovos','Tomate'],
    array['Prepare os ovos mexidos.','Monte com o pao e o tomate.']
  ),
  (
    'Cottage com banana e aveia',
    'ganhar_massa',
    'lanche_tarde',
    340,
    20,
    4,
    false,
    '',
    true,
    array['rapido','pre_treino'],
    array['4 colheres de cottage','1 banana','2 colheres de aveia'],
    array['Misture tudo em uma tigela.','Consuma em seguida.']
  ),

  (
    'Arroz, ovos e carne moida',
    'ganhar_massa',
    'jantar',
    690,
    42,
    25,
    false,
    '',
    true,
    array['economico','pos_treino'],
    array['100g arroz','3 ovos','140g carne moida'],
    array['Prepare a carne moida.','Cozinhe os ovos ou faca mexidos.','Sirva com arroz.']
  ),
  (
    'Frango com mandioca cozida',
    'ganhar_massa',
    'jantar',
    650,
    39,
    28,
    false,
    '',
    true,
    array['pos_treino'],
    array['160g frango grelhado','180g mandioca cozida','Salada'],
    array['Grelhe o frango.','Cozinhe a mandioca.','Sirva com salada.']
  ),
  (
    'Macarrao com atum e legumes',
    'ganhar_massa',
    'jantar',
    620,
    35,
    20,
    false,
    '',
    true,
    array['pos_treino'],
    array['120g macarrao','1 lata de atum','Legumes picados'],
    array['Cozinhe o macarrao.','Misture com atum e legumes refogados.']
  ),
  (
    'Crepioca de frango com queijo',
    'ganhar_massa',
    'jantar',
    540,
    34,
    15,
    false,
    '',
    true,
    array['pre_treino','pos_treino'],
    array['1 ovo','3 colheres de tapioca','100g frango desfiado','40g queijo branco'],
    array['Misture o ovo com a tapioca.','Prepare a base na frigideira.','Recheie com frango e queijo.']
  ),
  (
    'Patinho com arroz integral e feijao',
    'ganhar_massa',
    'jantar',
    710,
    43,
    27,
    false,
    '',
    true,
    array['economico','pos_treino'],
    array['150g patinho','100g arroz integral','80g feijao'],
    array['Grelhe o patinho.','Aqueça arroz e feijao.','Monte o prato.']
  )
),
inserted as (
  insert into public.receitas (
    titulo,
    objetivo,
    refeicao,
    calorias,
    proteina_g,
    tempo_preparo_min,
    is_premium,
    image_url,
    ativo,
    categorias
  )
  select
    titulo,
    objetivo,
    refeicao,
    calorias,
    proteina_g,
    tempo_preparo_min,
    is_premium,
    image_url,
    ativo,
    categorias
  from seed
  returning id, titulo, objetivo, refeicao
),
ingredientes as (
  insert into public.receita_ingredientes (receita_id, descricao, ordem)
  select
    i.id,
    ingrediente.descricao,
    ingrediente.ordem
  from inserted i
  join seed s
    on s.titulo = i.titulo
   and s.objetivo = i.objetivo
   and s.refeicao = i.refeicao
  cross join lateral unnest(s.ingredientes) with ordinality as ingrediente(descricao, ordem)
  returning receita_id
)
insert into public.receita_preparo (receita_id, passo, ordem)
select
  i.id,
  passo.descricao,
  passo.ordem
from inserted i
join seed s
  on s.titulo = i.titulo
 and s.objetivo = i.objetivo
 and s.refeicao = i.refeicao
cross join lateral unnest(s.preparo) with ordinality as passo(descricao, ordem);

commit;
